# Scrum Project Labels Configuration
# This file documents the labels used in this project
# You can use the GitHub Labels API or UI to create these labels

## Type Labels
- name: epic
  color: '3E4B9E'
  description: 'Large feature spanning multiple sprints'

- name: user-story
  color: '0E8A16'
  description: 'User story following the format: As a [user], I want [goal] so that [benefit]'

- name: task
  color: '1D76DB'
  description: 'Technical task'

- name: bug
  color: 'D73A4A'
  description: 'Something is not working'

## Priority Labels
- name: priority-high
  color: 'B60205'
  description: 'High priority'

- name: priority-medium
  color: 'FBCA04'
  description: 'Medium priority'

- name: priority-low
  color: '0E8A16'
  description: 'Low priority'

## Status Labels
- name: blocked
  color: 'D93F0B'
  description: 'Work is blocked by dependencies or issues'

- name: in-progress
  color: 'FBCA04'
  description: 'Currently being worked on'

- name: in-review
  color: '5319E7'
  description: 'In code review or testing'

- name: needs-discussion
  color: 'D876E3'
  description: 'Needs team discussion'

- name: ready
  color: '0E8A16'
  description: 'Ready to be worked on'

## Sprint Labels
- name: sprint-1
  color: 'C5DEF5'
  description: 'Sprint 1'

- name: sprint-2
  color: 'C5DEF5'
  description: 'Sprint 2'

- name: sprint-3
  color: 'C5DEF5'
  description: 'Sprint 3'

- name: backlog
  color: 'EDEDED'
  description: 'Product backlog'

## Other Labels
- name: documentation
  color: '0075CA'
  description: 'Improvements or additions to documentation'

- name: duplicate
  color: 'CFD3D7'
  description: 'This issue or pull request already exists'

- name: enhancement
  color: 'A2EEEF'
  description: 'New feature or request'

- name: good-first-issue
  color: '7057FF'
  description: 'Good for newcomers'

- name: help-wanted
  color: '008672'
  description: 'Extra attention is needed'

- name: invalid
  color: 'E4E669'
  description: 'This does not seem right'

- name: question
  color: 'D876E3'
  description: 'Further information is requested'

- name: wontfix
  color: 'FFFFFF'
  description: 'This will not be worked on'

- name: stale
  color: 'EEEEEE'
  description: 'No recent activity'

- name: retrospective
  color: 'F9D0C4'
  description: 'Sprint retrospective item'
